const diccionarioTI = {
  "bgp": "Protocolo que intercambia información de rutas entre redes distintas. Es esencial para el funcionamiento de Internet.",
  "dns": "Sistema que traduce nombres de dominio legibles (como google.com) en direcciones IP que usan los equipos para comunicarse.",
  "nat": "Método que permite que varios dispositivos compartan una sola dirección IP pública para acceder a Internet.",
  "ping": "Herramienta que permite verificar si un dispositivo en red está disponible y cuánto tarda en responder.",
  "latency": "Tiempo que tarda un dato en ir y volver entre dos puntos de red. Menor latencia implica mejor respuesta.",
  "firewall": "Sistema que controla qué tráfico puede entrar o salir de una red, según reglas definidas para protegerla.",
  "ipsec": "Conjunto de protocolos que cifran datos enviados por redes IP para asegurar la privacidad y autenticidad.",
  "traceroute": "Herramienta que muestra el camino que sigue un paquete de datos a través de la red hasta su destino.",
  "api": "Interfaz que permite que dos sistemas diferentes se comuniquen e intercambien información de forma controlada.",
  "json": "Formato de texto utilizado para estructurar e intercambiar datos entre sistemas de forma sencilla.",
  "rest": "Estilo de arquitectura que usa HTTP para permitir la comunicación entre sistemas de forma estándar y sencilla.",
  "docker": "Plataforma que permite empaquetar aplicaciones con todas sus dependencias para ejecutarlas en cualquier entorno.",
  "kubernetes": "Sistema que automatiza la gestión de aplicaciones en contenedores, incluyendo su despliegue y escalado.",
  "sla": "Acuerdo formal que define el nivel de servicio esperado entre proveedor y cliente, incluyendo tiempos de respuesta.",
  "bsod": "Mensaje de error crítico en Windows que obliga a reiniciar el sistema. Indica una falla grave.",
  "vm": "Software que emula un computador físico, permitiendo ejecutar varios sistemas operativos en una misma máquina.",
  "rdp": "Protocolo que permite controlar remotamente otro computador con una interfaz gráfica.",
  "tls": "Protocolo de cifrado que protege la transmisión de datos en internet, usado comúnmente en sitios web seguros.",
  "yaml": "Formato de archivo usado para configurar sistemas y aplicaciones, legible para humanos.",
  "kernel": "Núcleo del sistema operativo que gestiona el hardware y los recursos del sistema.",
  "ps": "Comando que muestra los procesos en ejecución en un sistema operativo tipo Unix o Linux.",
  "top": "Herramienta que permite ver en tiempo real el uso de recursos del sistema por cada proceso.",
  "grep": "Herramienta que busca texto dentro de archivos o resultados, útil para filtrar información específica.",
  "awk": "Lenguaje de programación para procesamiento y análisis de texto en línea de comandos.",
  "sed": "Herramienta que permite editar texto desde la línea de comandos de forma automatizada.",
  "icmp": "Protocolo usado por herramientas como ping para enviar mensajes de control y diagnóstico en redes.",
  "mtu": "Tamaño máximo de datos que se pueden enviar en un solo paquete por la red sin fragmentación.",
  "syslog": "Protocolo para registrar eventos y mensajes del sistema en un servidor central o archivo.",
  "snmp": "Protocolo usado para monitorear y administrar dispositivos de red como routers y switches.",
  "uptime": "Cantidad de tiempo que un sistema ha estado en funcionamiento continuo sin reiniciarse.",
  "whoami": "Comando que muestra el nombre del usuario que está ejecutando una sesión de terminal.",
  "hostname": "Nombre único que identifica a un dispositivo en una red.",
  "cron": "Servicio que ejecuta tareas programadas automáticamente en momentos definidos.",
  "cronjob": "Tarea programada para ejecutarse automáticamente en momentos específicos definidos por el usuario.",
  "loopback": "Interfaz de red que representa al propio dispositivo. Usada para pruebas o servicios internos.",
  "fqdn": "Nombre de dominio completo que identifica a un host en Internet de forma única.",
  "ssh": "Protocolo seguro para conectarse a otro equipo de forma remota mediante línea de comandos.",
  "ftp": "Protocolo para transferencia de archivos entre equipos en red. No incluye cifrado de datos.",
  "sftp": "Versión segura de FTP que cifra los datos transferidos.",
  "vlan": "Segmentación lógica de una red física para mejorar seguridad y administración.",
  "subnet": "División de una red en segmentos más pequeños para optimizar el uso y control de direcciones IP.",
  "cidr": "Forma compacta de representar rangos de direcciones IP y máscaras de red.",
  "route": "Camino que sigue un paquete de datos desde el origen hasta el destino en una red.",
  "gateway": "Dispositivo que conecta una red local con otras redes, generalmente hacia Internet.",
  "dhcp": "Protocolo que asigna automáticamente direcciones IP a los dispositivos en una red.",
  "ipv6": "Versión moderna del protocolo IP, con un espacio de direcciones mucho mayor que IPv4.",
  "arp": "Protocolo que relaciona direcciones IP con direcciones físicas (MAC) en redes locales.",
  "mac address": "Dirección física única que identifica a una interfaz de red en un dispositivo.",
  "spoofing": "Técnica maliciosa que suplanta la identidad de un dispositivo o usuario en red.",
  "dos": "Ataque que busca dejar fuera de servicio a un sistema saturándolo de solicitudes.",
  "ddos": "Ataque de denegación de servicio realizado desde múltiples fuentes simultáneamente.",
  "honeypot": "Sistema intencionadamente vulnerable, usado como trampa para detectar o analizar ataques.",
  "ids": "Sistema que detecta accesos o actividades no autorizadas en una red o sistema.",
  "ips": "Sistema que detecta y bloquea automáticamente amenazas en la red.",
  "token": "Código de acceso temporal que autentica a un usuario o sistema para acceder a un servicio.",
  "hash": "Valor único calculado a partir de un dato, usado para verificar integridad o almacenar contraseñas.",
  "ldap": "Protocolo para acceder y mantener servicios de directorio, como listas de usuarios en redes empresariales.",
  "active directory": "Servicio de directorio de Microsoft que gestiona usuarios, equipos y recursos en redes Windows.",
  "2fa": "Método de autenticación que requiere dos pruebas de identidad, como contraseña y código SMS.",
  "mfa": "Autenticación multifactor, que exige múltiples formas de verificación para mayor seguridad.",
  "token jwt": "Formato estándar para enviar datos de autenticación entre sistemas de forma segura.",
  "saml": "Protocolo que permite autenticación única entre aplicaciones, común en entornos corporativos.",
  "radius": "Protocolo que centraliza la autenticación y autorización de usuarios en redes.",
  "iam": "Gestión de identidades y accesos, controlando quién puede hacer qué dentro de sistemas.",
  "zero trust": "Modelo de seguridad que no confía en nada por defecto, ni siquiera dentro de la red interna.",
  "vpn": "Tecnología que crea una conexión segura y cifrada entre el usuario y una red privada.",
  "proxy": "Servidor intermedio que gestiona solicitudes entre el usuario y otros servicios de red.",
  "reverse proxy": "Servidor que recibe solicitudes desde Internet y las dirige a servidores internos.",
  "load balancer": "Dispositivo o software que distribuye el tráfico entre varios servidores para mejorar rendimiento.",
  "container": "Entorno aislado que ejecuta una aplicación con sus dependencias, de forma liviana.",
  "microservicio": "Modelo de desarrollo donde una aplicación se divide en pequeños servicios independientes.",
  "service mesh": "Infraestructura para gestionar comunicaciones entre microservicios, con seguridad y monitoreo.",
  "orquestación": "Automatización de despliegues, escalado y gestión de aplicaciones en contenedores.",
  "ci": "Integración continua: proceso que verifica automáticamente cambios en el código para asegurar calidad.",
  "cd": "Entrega continua: automatiza la publicación de software en producción tras cada cambio aprobado.",
  "devops": "Cultura y conjunto de prácticas que unifican desarrollo y operaciones para mejorar entregas.",
  "observabilidad": "Capacidad de entender el estado interno de un sistema a través de métricas, logs y trazas.",
  "log": "Registro de eventos generados por aplicaciones o sistemas para diagnóstico y auditoría.",
  "metric": "Valor numérico que representa el comportamiento de un sistema o servicio.",
  "alerta": "Notificación que avisa sobre un comportamiento anómalo o umbral superado en un sistema.",
  "traza": "Seguimiento detallado de la ejecución de una petición a través de varios servicios.",
  "slo": "Objetivo de nivel de servicio, define metas medibles como disponibilidad o tiempo de respuesta.",
  "sla breach": "Incumplimiento de los términos acordados de servicio, como superar el tiempo de respuesta.",
  "drp": "Plan de recuperación ante desastres que asegura la continuidad del negocio tras fallos graves.",
  "ha": "Alta disponibilidad: diseño de sistemas que minimiza el tiempo fuera de servicio.",
  "clustering": "Técnica que agrupa servidores para trabajar como una sola unidad y mejorar disponibilidad.",
  "failover": "Cambio automático a un sistema de respaldo cuando ocurre una falla en el principal.",
  "backup": "Copia de seguridad de datos para restaurarlos en caso de pérdida o corrupción.",
  "snapshot": "Captura del estado de un sistema o datos en un momento específico.",
  "replicación": "Copia de datos entre sistemas para redundancia o alta disponibilidad.",
  "nas": "Almacenamiento conectado a red, accesible por múltiples dispositivos.",
  "san": "Red dedicada de almacenamiento que proporciona acceso de alto rendimiento a discos.",
  "ssd": "Unidad de almacenamiento rápido sin partes móviles, común en servidores modernos.",
  "iops": "Cantidad de operaciones de entrada/salida por segundo que un sistema de almacenamiento puede manejar.",
  "throughput": "Cantidad de datos que un sistema puede procesar en un período de tiempo.",
  "latencia de disco": "Tiempo que tarda un disco en responder a una solicitud de lectura o escritura.",
  "hypervisor": "Software que permite ejecutar múltiples máquinas virtuales en un solo servidor físico.",
  "bare metal": "Servidor físico sin virtualización. Ofrece máximo rendimiento dedicado.",
  "provisionamiento": "Proceso de preparar e implementar recursos tecnológicos, como servidores o servicios.",
  "infraestructura como código": "Gestión automática de infraestructura mediante archivos de configuración.",
  "terraform": "Herramienta que permite definir y desplegar infraestructura como código en múltiples plataformas.",
  "ansible": "Herramienta de automatización que gestiona configuraciones y despliegues desde archivos YAML.",
  "puppet": "Sistema de automatización de configuración usado para administrar servidores.",
  "chef": "Herramienta para automatizar infraestructuras y mantener configuraciones consistentes.",
  "bash": "Intérprete de comandos para sistemas Unix/Linux, usado para automatización de tareas.",
  "shell": "Interfaz que permite interactuar con el sistema operativo mediante comandos.",
  "endpoint": "Dispositivo final que se conecta a la red, como computadores, móviles o tablets.",
  "patch": "Actualización de software que corrige errores o vulnerabilidades.",
  "vulnerability": "Debilidad en un sistema que puede ser explotada para comprometer su seguridad.",
  "exploit": "Código o técnica usada para aprovechar una vulnerabilidad y obtener acceso no autorizado."
};